version: '3.9'

services:
 
  db:
    image: postgres
    container_name: pgdb
    restart: always
    shm_size: 128mb
    env_file: .env
    volumes:
    - pgdata:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    container_name: admin
    ports:
      - 8080:8080
 
volumes:
  pgdata:
 
